channels:
  - conda-forge
  - cadquery
  - set3mah

dependencies:
  - python
  - pyvista
  - cadquery=master
  - python-gmsh
  - meshio
  - mmg
  - neper
  - pytest-cov
  - libtiff<4.4

