channels:
  - conda-forge
  - cadquery
  - set3mah

dependencies:
  - cadquery=master
  - vtk
  - pyvista
  - python-gmsh
  - meshio
  - mmg
  - neper # [unix]
  - pytest-cov
  - libtiff<4.4

