channels:
  - conda-forge
  - cadquery
  - set3mah

dependencies:
  - python
  - vtk=9.0.1
  - pyvista
  - cadquery=master
  - python-gmsh
  - meshio
  - mmg
  - neper # [unix]
  - pytest-cov
  - libtiff<4.4
  # mybinder
  - ipygany
  - mesa-libgl-devel-cos7-x86_64
  - pywin32 # [win]
  - pip:
    - jupyter-cadquery

