name: microgen
channels:
  - conda-forge
  - set3mah

dependencies:
  - numpy
  - vtk >=9.4
  - pyvista
  - matplotlib
  - scipy
  - python-gmsh
  - meshio
  - cadquery
  - mmg
#  - neper
