channels:
  - conda-forge
  - cadquery
  - set3mah

dependencies:
  - python
  - vtk=9.0.1
  - cadquery=master
  - python-gmsh=4.8
  - pygalmesh
  - mmg
  - neper
  - pytest-cov
  - libtiff<4.4
  - pyvista
