{% set name = "mmg" %}
{% set version = "5.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: https://github.com/MmgTools/mmg.git

build:
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - make # [unix]
    
about:
  home: https://github.com/MmgTools/mmg
  license: LGPL-3.0-or-later
  license_family: LGPL
  license_file: LICENSE
  summary: 'Libraries and applications for simplicial mesh adaptation'
  description: |
    Mmg gather open-source software for simplicial mesh modifications (2D, 3D surfacic and 3D volumic). |
    It allows for: mesh quality improvement, mesh adaptation on an isotropic or anisotropic sizemap, isovalue discretization, and Lagrangian movement.
  doc_url: https://www.mmgtools.org/mmg-remesher-try-mmg
  dev_url: https://github.com/MmgTools/mmg

extra:
  recipe-maintainers:
    - Algiane
