name: docs
channels:
  - conda-forge
  - cadquery
  - set3mah

dependencies:
  - microgen=1.0.1
  - pyvista>=0.39
  - cadquery=2.3.1
  - occt=7.7.0
  - meshio
  - pythreejs=2.3.0
  - jupyter-sphinx
  - pip
  - pip:
    - sphinx_rtd_theme
