name: docs
channels:
  - conda-forge
  - set3mah

dependencies:
  - python=3.11
  - microgen=1.0.1
  - pyvista>=0.39
  - cadquery=2.3.1
  - occt=7.7.0
  - meshio=5.3.4
  # - pythreejs=2.3.0
  - jupyter-sphinx=0.4.0
  - pip
  - pip:
    - sphinx_rtd_theme=1.3.0
