package:
  name: microgen
  version: 1.0.1

source:
  git_url: https://github.com/3MAH/microgen.git

build:
  # noarch: python
  script: python setup.py install

requirements:
  host:
    - python
  run:
    - cadquery=merge
    - pyvista
    - python-gmsh
    - meshio
    - mmg
    - neper # [unix]
    - pytest-cov

test:
  imports:
    - microgen
  source_files:
    - tests
    - examples
  commands:
    - pytest tests
