package:
  name: microgen
  version: 1.0.0

source:
  git_url: https://github.com/3MAH/microgen.git

build:
  noarch: python

requirements:
  host:
    - python
  run:
    - python
    - cadquery=master
    - python-gmsh
    - pygalmesh
    - mmg

test:
  imports:
    - microgen
  source_files:
    - examples/mmg
  commands:
    - cd $SRC_DIR/examples/mmg
    - $PYTHON test_mmg.py
          
    - cd $SRC_DIR/examples/mmg-voro
    - $PYTHON test_mmg.py
          
    - cd $SRC_DIR/examples/octetTruss
    - $PYTHON testOctet.py
          
    - cd $SRC_DIR/examples/rasterEllipsoid
    - $PYTHON rasterEllipsoid.py
          
    - cd $SRC_DIR/examples/rasterGyroid
    - $PYTHON rasterGyroid.py
          
    - cd $SRC_DIR/examples/triplyPeriodicMinimalSurfaces
    - $PYTHON testTPMS.py
          
    - cd $SRC_DIR/examples/Voronoi
    - $PYTHON testNeper.py
