package:
  name: microgen
  version: 1.0.0

source:
  git_url: https://github.com/3MAH/microgen.git

build:
  # noarch: python
  script: python setup.py install

requirements:
  host:
    - python
  run:
    - python
    - vtk=9.0.1
    - cadquery=master
    - python-gmsh
    - mmg
    - neper # [unix]
    - pytest-cov
    - libtiff<4.4
    - pyvista
    - meshio

test:
  imports:
    - microgen
  source_files:
    - tests
    - examples
  commands:
    - pytest tests
