package:
  name: microgen
  version: 1.0.0

source:
  git_url: https://github.com/3MAH/microgen.git

build:
  noarch: python

requirements:
  build:
    - python
    - setuptools
  host:
    - python
    - pip
  run:
    - python
    - pygalmesh
    - gmsh
    - python-gmsh
    - numpy
    - cadquery>=2

test:
  imports:
    - microgen
