package:
  name: microgen
  version: {{ environ.get('PACKAGE_VERSION') }}

source:
  git_url: https://github.com/3MAH/microgen.git
  git_tag: {{ environ.get('BRANCH_NAME') }}

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8,<3.12
    - pip
  run:
    - python >=3.8,<3.12
    - numpy
    - vtk
    - pyvista
    - python-gmsh
    - meshio
    - cadquery
    - scipy

test:
  imports:
    - microgen
  requires:
    - pytest
  source_files:
    - tests
    - examples/BasicShapes/platon/tetrahedron.obj
  commands:
    - pytest tests

about:
  home: https://github.com/3MAH/microgen
  summary: 'Microstructure generation'
  description: |
    Microgen is a Python library designed to facilitate microstructure generation and meshing.
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  doc_url: https://microgen.readthedocs.io
  dev_url: https://github.com/3MAH/microgen

extra:
  recipe-maintainers:
    - kmarchais
    - chemiskyy
    - ricardo0115
