{% set version = "1.0.1" %}

package:
  name: microgen
  version: {{ version }}

source:
  git_url: https://github.com/3MAH/microgen.git

build:
  noarch: python
  script: pip install .

requirements:
  host:
    - python
    - pip    
  run:
    - pyvista>=0.39
    - python-gmsh
    - meshio
    - cadquery
    - pytest-cov
#    - mmg
#    - neper

test:
  imports:
    - microgen
  source_files:
    - tests
    - examples
    - conda.recipe/meta.yaml
  commands:
    - pytest tests
