package:
  name: microgen
  version: 1.0.0

source:
  git_url: https://github.com/3MAH/microgen.git
  git_tag: mmg

build:
  noarch: python
  string: mmg

requirements:
  host:
    - python
  run:
    - python
    - cadquery=2
    - python-gmsh
    - pygalmesh
    - mmg

test:
  imports:
    - microgen
