{% set version = "1.0.1" %}

package:
  name: microgen
  version: {{ version }}

source:
  git_url: ../

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  string: {{ environ.get('PR_NUMBER') }}

requirements:
  host:
    - python >=3.8
    - pip    
  run:
    - python >=3.8
    - numpy
    - pyvista
    - python-gmsh
    - meshio
    - cadquery
    - scipy

test:
  imports:
    - microgen
  commands:
    # - pip check
  requires:
    - pip

about:
  home: https://github.com/3MAH/microgen
  summary: 'Microstructure generation'
  description: |
    Microstructure generation.
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  doc_url: https://microgen.readthedocs.io
  dev_url: https://github.com/3MAH/microgen

extra:
  recipe-maintainers:
    - kmarchais
