name: Create conda package

on:
  workflow_dispatch:
  release:
    types: [published]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  conda-packaging:
    name: Conda packaging
    runs-on: "windows-latest"
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          miniconda-version: "latest"
          activate-environment: packaging

      - name: Conda build
        shell: bash -l {0}
        run: |
          conda install -y conda-build anaconda-client
          conda config --set anaconda_upload no
          conda-build conda.recipe -c conda-forge --output-folder .

      - name: Upload to Anaconda
        shell: bash -l {0}
        env:
          ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_API_TOKEN }}
        run: |
          anaconda upload noarch/*.conda --force --no-progress
