name: Create conda package

on:
  workflow_dispatch:
  push:
    branches:
      - "*"

jobs:
  conda-packaging:
    name: Conda packaging
    runs-on: "ubuntu-latest"
    env:
      BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v2
        with:
          miniconda-version: "latest"
          activate-environment: packaging

      # - name: Extract PR number
      #   if: ${{ github.event.issue.pull_request }}
      #   shell: pwsh
      #   run: echo $env:CONDA_BUILD_STRING
      #   env:
      #     CONDA_BUILD_STRING: "PR_${{ github.event.issue.number }}"
      - name: Conda build
        shell: bash
        run: |
          CONDA_BUILD_STRING="${{ github.head_ref || github.ref_name }}//-/_"
          echo "branch name $CONDA_BUILD_STRING"
          conda install python conda-build conda-verify anaconda-client
          anaconda logout
          anaconda login --username ${{ secrets.ANACONDA_USERNAME }} --password ${{ secrets.ANACONDA_PASSWORD }}
          conda-build conda.recipe -c conda-forge --output-folder  .
          anaconda upload noarch/*.tar.bz2 --force
        # env:
        #   CONDA_BUILD_STRING: ${{ env.CONDA_BUILD_STRING }}
