name: Create conda package

on:
  workflow_dispatch:
  release:
    types: [published]
  push:
    branches:
      - "*"

jobs:
  conda-packaging:
    name: Conda packaging
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v2
        with:
          miniconda-version: "latest"
          activate-environment: packaging

      - name: Conda build
        shell: bash -l {0}
        run: |
          export PACKAGE_VERSION="${BRANCH_NAME//-/_}"
          conda install python conda-build conda-verify anaconda-client
          anaconda login --username ${{ secrets.ANACONDA_USERNAME }} --password ${{ secrets.ANACONDA_PASSWORD }}
          conda-build conda.recipe -c conda-forge --output-folder  .
          anaconda upload noarch/*.tar.bz2 --force
          anaconda logout
        env:
          BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
