name: Create conda package

on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - "*"

jobs:
  conda-packaging:
    name: Conda packaging
    runs-on: "windows-latest"
    env:
      BRANCH_NAME: ${{ steps.extract_branch.outputs.branch }}
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v2
        with:
          miniconda-version: "latest"
          activate-environment: packaging
      - name: Extract branch name
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch
      - name: Conda build
        shell: pwsh
        run: |
          conda install python conda-build conda-verify anaconda-client
          anaconda logout
          anaconda login --username ${{ secrets.ANACONDA_USERNAME }} --password ${{ secrets.ANACONDA_PASSWORD }}
          conda-build conda.recipe -c conda-forge --output-folder  .
          anaconda upload noarch/*.tar.bz2 --force
