name: Create conda package

on:
  workflow_dispatch:
  release:
    types: [published]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: ${{ matrix.os }} (${{ matrix.conda_platform }})
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: Linux
            runner: ubuntu-latest
            conda_platform: noarch

    steps:
      - uses: actions/checkout@v4

      - uses: conda-incubator/setup-miniconda@v3
        with:
          miniforge-version: latest
          activate-environment: packaging
          auto-update-conda: true
          conda-solver: libmamba

      - name: Build Package
        shell: bash -l {0}
        run: |
          conda install -y conda-build conda-verify
          conda config --set anaconda_upload no
          conda-build conda.recipe -c conda-forge --output-folder .

      - name: Upload to Anaconda
        shell: bash -l {0}
        env:
          ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_API_TOKEN }}
        run: |
          conda install -y anaconda-client
          anaconda upload ${{ matrix.conda_platform }}/*.conda --force --no-progress
