name: Create conda package for mmg

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  Linux:
    name: Linux
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          miniconda-version: "latest"
          activate-environment: packaging
      - name: Conda build for Linux
        shell: bash -l {0}
        run: |
          conda install python=3.12 conda-build anaconda-client
          conda config --set anaconda_upload no
          conda-build mmg.recipe -c conda-forge -c set3mah --output-folder .
      - name: Upload to Anaconda
        shell: bash -l {0}
        env:
          ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_TOKEN }}
        run: |
          anaconda upload linux-64/*.conda --force --no-progress

  macos:
    name: MacOS
    runs-on: "macos-latest"
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          miniconda-version: "latest"
          activate-environment: packaging
      - name: Conda build for MacOS
        shell: bash -l {0}
        run: |
          conda install python=3.12 conda-build anaconda-client
          conda config --set anaconda_upload no
          conda-build mmg.recipe -c conda-forge -c set3mah --output-folder .
      - name: Upload to Anaconda
        shell: bash -l {0}
        env:
          ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_TOKEN }}
        run: |
          anaconda upload osx-arm64/*.conda --force --no-progress

  windows:
    name: Windows
    runs-on: "windows-latest"
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          miniconda-version: "latest"
          activate-environment: packaging
      - name: Conda build for Windows
        shell: bash -l {0}
        run: |
          conda install python=3.12 conda-build anaconda-client
          conda config --set anaconda_upload no
          conda-build mmg.recipe -c conda-forge -c set3mah --output-folder .
      - name: Upload to Anaconda
        shell: bash -l {0}
        env:
          ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_TOKEN }}
        run: |
          anaconda upload win-64/*.conda --force --no-progress
