name: Create conda package for mmg

on:
  workflow_dispatch:

jobs:
  Linux:
    name: Linux
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          miniconda-version: "latest"
          auto-update-conda: true

      - name: Install Dependencies
        shell: bash -l {0}
        run: |
          conda update --all
          conda clean --all
          conda install conda-build anaconda-client conda-verify
          conda config --set anaconda_upload no

      - name: Build Package
        shell: bash -l {0}
        run: |
          conda-build mmg.recipe -c set3mah -c conda-forge --no-test --output-folder  .

      - name: Upload to Anaconda
        shell: bash -l {0}
        env:
          ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_TOKEN }}
        run: |
          anaconda upload linux-64/*.conda --force
