name: Create conda package for neper

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  Linux:
    name: Linux
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          miniconda-version: "latest"
          activate-environment: packaging
      - name: Conda build for Linux
        shell: bash -l {0}
        run: |
          conda install python=3.12 conda-build anaconda-client
          conda-build neper.recipe -c conda-forge -c set3mah --output-folder .
          anaconda upload --token ${{ secrets.ANACONDA_API_TOKEN }} linux-64/neper-*.conda --force

  macos:
    name: MacOS
    runs-on: "macos-latest"
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          miniconda-version: "latest"
          activate-environment: packaging
      - name: Conda build for MacOS
        shell: bash -l {0}
        run: |
          conda install python=3.12 conda-build anaconda-client
          conda-build neper.recipe -c conda-forge -c set3mah --output-folder .
          anaconda upload --token ${{ secrets.ANACONDA_API_TOKEN }} osx-arm64/neper-*.conda --force

  windows:
    name: Windows
    runs-on: "windows-latest"
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          miniconda-version: "latest"
          activate-environment: packaging
      - name: Conda build for Windows
        shell: bash -l {0}
        run: |
          conda install python=3.12 conda-build anaconda-client
          conda-build neper.recipe -c conda-forge -c set3mah --output-folder .
          anaconda upload --token ${{ secrets.ANACONDA_API_TOKEN }} win-64/neper-*.conda --force
