name: Create conda package for neper

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: ${{ matrix.os }} (${{ matrix.conda_platform }})
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: Linux
            runner: ubuntu-latest
            conda_platform: linux-64
          - os: MacOS
            runner: macos-latest
            conda_platform: osx-arm64
          - os: Windows
            runner: windows-latest
            conda_platform: win-64

    steps:
      - uses: actions/checkout@v4

      - uses: conda-incubator/setup-miniconda@v3
        with:
          miniforge-version: latest
          activate-environment: packaging
          auto-update-conda: true
          conda-solver: libmamba

      - name: Build Package
        shell: bash -l {0}
        run: |
          conda install -y conda-build
          conda config --set anaconda_upload no
          conda-build neper.recipe -c conda-forge -c set3mah --no-test --output-folder .

      - name: Upload to Anaconda
        shell: bash -l {0}
        env:
          ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_API_TOKEN }}
        run: |
          conda install -y anaconda-client
          anaconda upload ${{ matrix.conda_platform }}/*.conda --force --no-progress
