name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: foo
          channels: conda-forge, cadquery, set3mah
      - name: Install
        run: |
          conda install python=3.8 cadquery=master python-gmsh pygalmesh mmg
          python setup.py install
