"""Microstructure generation package."""

import importlib.metadata

from .box_mesh import BoxMesh, NonBoxMeshError
from .external import Mmg, Neper
from .mesh import is_periodic, mesh, mesh_periodic
from .operations import (
    cut_phase_by_shape_list,
    cut_phases,
    cut_phases_by_shape,
    cut_shapes,
    fuse_shapes,
    raster_phase,
    repeat_polydata,
    repeat_shape,
    rescale,
    rotate,
    rotate_euler,
)
from .periodic import periodic_split_and_translate
from .phase import Phase
from .report import Report
from .rve import Rve
from .shape import (
    AbstractLattice,
    BodyCenteredCubic,
    Box,
    Capsule,
    Cubic,
    Cuboctahedron,
    CustomLattice,
    Cylinder,
    CylindricalTpms,
    Diamond,
    Ellipsoid,
    ExtrudedPolygon,
    FaceCenteredCubic,
    GradedInfill,
    Infill,
    NormedDistance,
    Octahedron,
    OctetTruss,
    Polyhedron,
    RhombicCuboctahedron,
    RhombicDodecahedron,
    Shape,
    Sphere,
    SphericalTpms,
    Spinodoid,
    Sweep,
    Tpms,
    TruncatedCube,
    TruncatedCuboctahedron,
    TruncatedOctahedron,
    batch_smooth_union,
    from_field,
    implicit_ops,
    new_geometry,
    surface_functions,
)
from .single_mesh import SingleMesh, check_if_only_linear_tetrahedral

__version__ = importlib.metadata.version(__package__ or __name__)

__all__ = [
    "AbstractLattice",
    "BodyCenteredCubic",
    "Box",
    "BoxMesh",
    "Capsule",
    "Cubic",
    "Cuboctahedron",
    "CustomLattice",
    "Cylinder",
    "Diamond",
    "Ellipsoid",
    "ExtrudedPolygon",
    "FaceCenteredCubic",
    "GradedInfill",
    "Infill",
    "NonBoxMeshError",
    "NormedDistance",
    "Mmg",
    "Neper",
    "Octahedron",
    "OctetTruss",
    "Phase",
    "Polyhedron",
    "RhombicCuboctahedron",
    "RhombicDodecahedron",
    "Rve",
    "Shape",
    "Sphere",
    "Spinodoid",
    "Sweep",
    "Tpms",
    "TruncatedCube",
    "TruncatedCuboctahedron",
    "TruncatedOctahedron",
    "CylindricalTpms",
    "SphericalTpms",
    "batch_smooth_union",
    "from_field",
    "implicit_ops",
    "check_if_only_linear_tetrahedral",
    "cut_phase_by_shape_list",
    "cut_phases",
    "cut_phases_by_shape",
    "cut_shapes",
    "fuse_shapes",
    "is_periodic",
    "mesh",
    "mesh_periodic",
    "new_geometry",
    "periodic_split_and_translate",
    "raster_phase",
    "repeat_polydata",
    "repeat_shape",
    "rescale",
    "rotate",
    "rotate_euler",
    "Report",
    "SingleMesh",
    "surface_functions",
]
