"""Wrappers around external command-line tools.

- `Neper - Polycrystal Generation and Meshing`_
- `mmg - Robust, Open-source & Multidisciplinary Software for Remeshing`_

.. _Neper - Polycrystal Generation and Meshing: https://neper.info/
.. _mmg - Robust, Open-source & Multidisciplinary Software for Remeshing: https://www.mmgtools.org/
"""

from __future__ import annotations

import shutil
import subprocess
import warnings
from dataclasses import dataclass, fields
from pathlib import Path
from typing import TYPE_CHECKING

import numpy as np

from microgen.shape import Polyhedron

if TYPE_CHECKING:
    from typing import TextIO

# Vertex-data row indices in the polyhedron-faces section of a .tess file.
_TESS_VERTEX_X_INDEX = 1
_TESS_VERTEX_Y_INDEX = 2
_TESS_VERTEX_Z_INDEX = 3
_TESS_VERTEX_STATE_INDEX = 4


# ---------------------------------------------------------------------------
# Neper
# ---------------------------------------------------------------------------


class Neper:
    """Wrapper around the ``neper`` command-line tool."""

    @staticmethod
    def run(
        filename: str,
        n_cells: int,
        cube_dim: tuple[float, float, float],
    ) -> None:
        r"""Run a neper tessellation from the command line.

        Equivalent to::

            neper -T -n n_cells -id 1 -dim 3 \
                  -domain 'cube(cube_dim[0], cube_dim[1], cube_dim[2])' \
                  -morpho gg -o filename

        :param filename: output file
        :param n_cells: number of cells of the tessellation
        :param cube_dim: see `neper's documentation`_

        .. _neper's documentation: https://neper.info/doc/neper_t.html#cmdoption-domain
        """
        neper = shutil.which("neper")
        if neper is None:
            warnings.warn(
                "Neper is not installed. "
                "Please install Neper before running this command.",
                stacklevel=2,
            )
            return

        try:
            subprocess.run([neper, "--version"], check=True)  # noqa: S603
        except subprocess.CalledProcessError:
            warnings.warn(
                "Neper is installed but '--version' failed.",
                stacklevel=2,
            )
            return

        cube = f"'cube({cube_dim[0]},{cube_dim[1]},{cube_dim[2]})'"
        command = [
            neper,
            "-T",
            "-n",
            str(n_cells),
            "-id",
            "1",
            "-dim",
            "3",
            "-domain",
            cube,
            "-morpho",
            "gg",
            "-o",
            filename,
        ]
        subprocess.run(command, check=True)  # noqa: S603

    @staticmethod
    def voronoi_from_tess_file(filename: str) -> list[Polyhedron]:
        """Build :class:`Polyhedron` shapes from a neper-generated .tess file."""
        polyhedra: list[Polyhedron] = []
        tess = Neper.parse_tess(filename)
        for cell_index in range(tess["cells"]["number_of_cells"]):
            global_face_indices = tess["polyhedra"]["faces"][cell_index]
            global_vertex_indices: list[int] = []
            for face_ind in global_face_indices:
                global_vertex_indices += tess["faces"]["vertices"][face_ind - 1]
            global_vertex_indices = sorted(dict.fromkeys(global_vertex_indices))

            vertices: list[tuple[float, float, float]] = [
                (
                    tess["vertices"]["ver_x"][ind - 1],
                    tess["vertices"]["ver_y"][ind - 1],
                    tess["vertices"]["ver_z"][ind - 1],
                )
                for ind in global_vertex_indices
            ]

            faces: list[dict[str, list[int]]] = []
            for face_ind in global_face_indices:
                face_vertices = tess["faces"]["vertices"][face_ind - 1]
                faces.append(
                    {
                        "vertices": [
                            global_vertex_indices.index(v) for v in face_vertices
                        ],
                    },
                )

            polyhedra.append(Polyhedron(dic={"vertices": vertices, "faces": faces}))
        return polyhedra

    @staticmethod
    def parse_tess(filename: str) -> dict[str, dict]:
        """Parse a tessellation (.tess) file generated by neper.

        Returns a dictionary with keys ``cells``, ``vertices``, ``edges``,
        ``faces``, ``polyhedra``. Follows the .tess structure from
        `neper's documentation`_.

        .. _neper's documentation: https://neper.info/doc/fileformat.html#tessellation-file-tess
        """
        path = Path(filename)
        if path.suffix == "":
            path = path.with_suffix(".tess")
        with path.open() as f:
            for _ in range(6):
                f.readline()
            cells = Neper._read_cells(f)
            vertices = Neper._read_vertices(f)
            edges = Neper._read_edges(f)
            faces = Neper._read_faces(f)
            polyhedra = Neper._read_polyhedra(f)
        return {
            "cells": cells,
            "vertices": vertices,
            "edges": edges,
            "faces": faces,
            "polyhedra": polyhedra,
        }

    @staticmethod
    def _read_cells(f: TextIO) -> dict:
        cells: dict = {"number_of_cells": int(f.readline())}
        n = cells["number_of_cells"]
        while True:
            tag = f.readline().rstrip()
            if tag == "  *id":
                cells["id"] = Neper._read_int_block(f, n)
            elif tag in {"  *mode", "  *modeid"}:
                cells["mode"] = Neper._read_int_block(f, n)
            elif tag == "  *seed":
                cells["seed"] = [Neper._parse_seed_row(f.readline()) for _ in range(n)]
            elif tag == "  *ori":
                cells["ori"] = {"descriptor": f.readline()}
                for _ in range(n):
                    data = f.readline().split()
                    cells["ori"]["cellid_param"] = [float(x) for x in data[:3]]
            elif tag in {"  *orispread", "  *lam"}:
                pass
            elif tag == "  *crysym":
                cells["crysym"] = f.readline()
            elif tag == " **vertex":
                return cells
            else:
                err_msg = f"tag {tag} not known"
                raise ValueError(err_msg)

    @staticmethod
    def _read_int_block(f: TextIO, count: int) -> list[int]:
        values: list[int] = []
        while len(values) < count:
            values.extend(int(x) for x in f.readline().split())
        return values

    @staticmethod
    def _parse_seed_row(line: str) -> dict:
        data = line.split()
        return {
            "seed_id": int(data[0]),
            "seed_x": float(data[1]),
            "seed_y": float(data[2]),
            "seed_z": float(data[3]),
            "seed_weight": float(data[_TESS_VERTEX_STATE_INDEX]),
        }

    @staticmethod
    def _read_vertices(f: TextIO) -> dict:
        n = int(f.readline())
        vertices: dict = {
            "total_number_of_vertices": n,
            "ver_id": [],
            "ver_x": [],
            "ver_y": [],
            "ver_z": [],
            "ver_state": [],
        }
        for _ in range(n):
            data = f.readline().split()
            vertices["ver_id"].append(int(data[0]))
            vertices["ver_x"].append(float(data[_TESS_VERTEX_X_INDEX]))
            vertices["ver_y"].append(float(data[_TESS_VERTEX_Y_INDEX]))
            vertices["ver_z"].append(float(data[_TESS_VERTEX_Z_INDEX]))
            vertices["ver_state"].append(int(data[_TESS_VERTEX_STATE_INDEX]))
        return vertices

    @staticmethod
    def _read_edges(f: TextIO) -> dict:
        f.readline()  # **edge
        n = int(f.readline().rstrip())
        edges: dict = {
            "total_number_of_edges": n,
            "edge_id": [],
            "ver_1": [],
            "ver_2": [],
            "edge_state": [],
        }
        for _ in range(n):
            data = f.readline().split()
            edges["edge_id"].append(int(data[0]))
            edges["ver_1"].append(int(data[1]))
            edges["ver_2"].append(int(data[2]))
            edges["edge_state"].append(int(data[3]))
        return edges

    @staticmethod
    def _read_faces(f: TextIO) -> dict:
        f.readline()  # **face
        n = int(f.readline().rstrip())
        faces: dict = {
            "total_number_of_faces": n,
            "face_id": [],
            "vertices": [],
            "edges": [],
        }
        for _ in range(n):
            data = f.readline().split()
            faces["face_id"].append(int(data[0]))
            n_ver = int(data[1])
            faces["vertices"].append([int(data[j + 2]) for j in range(n_ver)])
            data = f.readline().split()
            n_edg = int(data[0])
            faces["edges"].append(
                [int(np.abs(int(data[j + 1]))) for j in range(n_edg)],
            )
            f.readline()  # not reading this line
            f.readline()  # not reading this line
        return faces

    @staticmethod
    def _read_polyhedra(f: TextIO) -> dict:
        f.readline()  # **polyhedron
        n = int(f.readline().rstrip())
        polyhedra: dict = {
            "total_number_of_polyhedra": n,
            "poly_id": [],
            "faces": [],
        }
        for _ in range(n):
            data = f.readline().split()
            polyhedra["poly_id"] = int(data[0])
            n_fac = int(data[1])
            polyhedra["faces"].append(
                [int(np.abs(int(data[j + 2]))) for j in range(n_fac)],
            )
        return polyhedra


# ---------------------------------------------------------------------------
# Mmg
# ---------------------------------------------------------------------------


class MmgError(Exception):
    """Raised when an mmg command fails."""


# Maps dataclass field name -> mmg command-line flag.  ``None`` means flag-only
# (no value), other values mean the field's value is rendered into the cmd.
_MMG_FLAG_MAP: dict[str, str | None] = {
    "debug": "-d",
    "show_help": "-h",
    "memory": "-m",
    "verbosity": "-v",
    "val": "-val",
    "default": "-default",
    "input_file": "-in",
    "output_file": "-out",
    "solution_file": "-sol",
    "metric_file": "-met",
    "no_angle_detection": "-A",
    "angle_threshold": "-ar",
    "octree": "-octree",
    "hausd": "-hausd",
    "hgrad": "-hgrad",
    "hmax": "-hmax",
    "hmin": "-hmin",
    "hsiz": "-hsiz",
    "lagrangian": "-lag",
    "level_set": "-ls",
    "nofem": "-nofem",
    "no_insert": "-noinsert",
    "no_move": "-nomove",
    "no_surface": "-nosurf",
    "no_swap": "-noswap",
    "no_ridge": "-nr",
    "n_regions": "-nreg",
    "n_subdomain": "-nsd",
    "optim": "-optim",
    "optim_les": "-optimLES",
    "open_boundary": "-opnbdy",
    "rmc": "-rmc",
    "rebuild_normals": "-rn",
    "medit_3d": "-3dMedit",
}


@dataclass(frozen=True)
class MmgOptions:
    """Common command-line options for the mmg tools.

    Each field maps to one mmg CLI flag. Fields with ``bool`` defaults render as
    flag-only options (``-foo``); fields with optional value defaults render as
    ``-foo VALUE`` when set. Not every flag is accepted by every mmg variant
    (mmg2d, mmgs, mmg3d); see the
    `mmg documentation <https://www.mmgtools.org/mmg-remesher-try-mmg/mmg-remesher-options>`_.
    """

    debug: bool = False
    show_help: bool = False
    memory: int | None = None
    verbosity: int | None = None
    val: bool = False
    default: bool = False
    input_file: str | None = None
    output_file: str | None = None
    solution_file: str | None = None
    metric_file: str | None = None
    no_angle_detection: bool = False
    angle_threshold: float | None = None
    octree: int | None = None
    hausd: float | None = None
    hgrad: float | None = None
    hmax: float | None = None
    hmin: float | None = None
    hsiz: float | None = None
    lagrangian: int | None = None
    level_set: float | None = None
    nofem: bool = False
    no_insert: bool = False
    no_move: bool = False
    no_surface: bool = False
    no_swap: bool = False
    no_ridge: bool = False
    n_regions: int | None = None
    n_subdomain: int | None = None
    optim: bool = False
    optim_les: bool = False
    open_boundary: bool = False
    rmc: float | None = None
    rebuild_normals: bool = False
    medit_3d: int | None = None


# Per-tool whitelist of supported MmgOptions fields.
_MMG2D_FIELDS = {
    "debug",
    "show_help",
    "memory",
    "verbosity",
    "val",
    "default",
    "input_file",
    "output_file",
    "solution_file",
    "metric_file",
    "no_angle_detection",
    "angle_threshold",
    "hausd",
    "hgrad",
    "hmax",
    "hmin",
    "hsiz",
    "lagrangian",
    "level_set",
    "medit_3d",
    "no_insert",
    "no_move",
    "no_surface",
    "no_swap",
    "no_ridge",
    "n_regions",
    "n_subdomain",
    "optim",
    "open_boundary",
    "rmc",
}

_MMGS_FIELDS = {
    "debug",
    "show_help",
    "memory",
    "verbosity",
    "val",
    "default",
    "input_file",
    "output_file",
    "solution_file",
    "metric_file",
    "no_angle_detection",
    "angle_threshold",
    "hausd",
    "hgrad",
    "hmax",
    "hmin",
    "hsiz",
    "level_set",
    "no_insert",
    "no_move",
    "no_surface",
    "no_swap",
    "no_ridge",
    "n_regions",
    "n_subdomain",
    "optim",
    "rebuild_normals",
}

_MMG3D_FIELDS = {
    "debug",
    "show_help",
    "memory",
    "verbosity",
    "val",
    "default",
    "input_file",
    "output_file",
    "solution_file",
    "metric_file",
    "no_angle_detection",
    "angle_threshold",
    "octree",
    "hausd",
    "hgrad",
    "hmax",
    "hmin",
    "hsiz",
    "lagrangian",
    "level_set",
    "nofem",
    "no_insert",
    "no_move",
    "no_surface",
    "no_swap",
    "no_ridge",
    "n_regions",
    "n_subdomain",
    "optim",
    "optim_les",
    "open_boundary",
    "rmc",
    "rebuild_normals",
}


def _build_mmg_cmd(
    binary: str,
    options: MmgOptions,
    allowed: set[str],
) -> list[str]:
    """Render an :class:`MmgOptions` into an mmg CLI argument list."""
    cmd = [binary]
    for field in fields(options):
        if field.name not in allowed:
            continue
        value = getattr(options, field.name)
        flag = _MMG_FLAG_MAP[field.name]
        if isinstance(value, bool):
            if value:
                cmd.append(flag)
        elif value is not None:
            cmd.extend([flag, str(value)])
    return cmd


def _run_mmg_command(cmd: list[str]) -> None:
    """Run an mmg subprocess and raise :class:`MmgError` on failure."""
    binary = shutil.which(cmd[0])
    if binary is None:
        err_msg = f"mmg command '{cmd[0]}' not found in PATH"
        raise MmgError(err_msg)
    try:
        subprocess.check_output([binary, *cmd[1:]], stderr=subprocess.STDOUT)  # noqa: S603
    except (subprocess.CalledProcessError, FileNotFoundError) as error:
        joined = " ".join([binary, *cmd[1:]])
        err_msg = f"mmg command '{joined}' failed"
        raise MmgError(err_msg) from error


class Mmg:
    """Wrapper around the ``mmg2d_O3`` / ``mmgs_O3`` / ``mmg3d_O3`` binaries."""

    @staticmethod
    def mmg2d(options: MmgOptions | None = None) -> None:
        """Run ``mmg2d_O3`` from the command line."""
        opts = options if options is not None else MmgOptions()
        _run_mmg_command(_build_mmg_cmd("mmg2d_O3", opts, _MMG2D_FIELDS))

    @staticmethod
    def mmgs(options: MmgOptions | None = None) -> None:
        """Run ``mmgs_O3`` from the command line."""
        opts = options if options is not None else MmgOptions()
        _run_mmg_command(_build_mmg_cmd("mmgs_O3", opts, _MMGS_FIELDS))

    @staticmethod
    def mmg3d(options: MmgOptions | None = None) -> None:
        """Run ``mmg3d_O3`` from the command line."""
        opts = options if options is not None else MmgOptions()
        _run_mmg_command(_build_mmg_cmd("mmg3d_O3", opts, _MMG3D_FIELDS))
