"""Wrappers around external command-line tools.

- `Neper - Polycrystal Generation and Meshing`_
- `mmg - Robust, Open-source & Multidisciplinary Software for Remeshing`_

.. _Neper - Polycrystal Generation and Meshing: https://neper.info/
.. _mmg - Robust, Open-source & Multidisciplinary Software for Remeshing: https://www.mmgtools.org/
"""

from __future__ import annotations

import shutil
import subprocess
import warnings
from pathlib import Path
from typing import TYPE_CHECKING

import numpy as np

from microgen.shape import Polyhedron

if TYPE_CHECKING:
    from typing import TextIO

# Vertex-data row indices in the polyhedron-faces section of a .tess file.
_TESS_VERTEX_X_INDEX = 1
_TESS_VERTEX_Y_INDEX = 2
_TESS_VERTEX_Z_INDEX = 3
_TESS_VERTEX_STATE_INDEX = 4

# Seed-row index in the *cell seed* section.
_TESS_SEED_WEIGHT_INDEX = 4


# ---------------------------------------------------------------------------
# Neper
# ---------------------------------------------------------------------------


class Neper:
    """Wrapper around the ``neper`` command-line tool."""

    @staticmethod
    def run(
        filename: str,
        n_cells: int,
        cube_dim: tuple[float, float, float],
    ) -> None:
        r"""Run a neper tessellation from the command line.

        Equivalent to::

            neper -T -n n_cells -id 1 -dim 3 \
                  -domain 'cube(cube_dim[0], cube_dim[1], cube_dim[2])' \
                  -morpho gg -o filename

        :param filename: output file
        :param n_cells: number of cells of the tessellation
        :param cube_dim: see `neper's documentation`_

        .. _neper's documentation: https://neper.info/doc/neper_t.html#cmdoption-domain
        """
        neper = shutil.which("neper")
        if neper is None:
            warnings.warn(
                "Neper is not installed. "
                "Please install Neper before running this command.",
                stacklevel=2,
            )
            return

        try:
            subprocess.run([neper, "--version"], check=True)  # noqa: S603
        except subprocess.CalledProcessError:
            warnings.warn(
                "Neper is installed but '--version' failed.",
                stacklevel=2,
            )
            return

        cube = f"cube({cube_dim[0]},{cube_dim[1]},{cube_dim[2]})"
        command = [
            neper,
            "-T",
            "-n",
            str(n_cells),
            "-id",
            "1",
            "-dim",
            "3",
            "-domain",
            cube,
            "-morpho",
            "gg",
            "-o",
            filename,
        ]
        subprocess.run(command, check=True)  # noqa: S603

    @staticmethod
    def voronoi_from_tess_file(filename: str) -> list[Polyhedron]:
        """Build :class:`Polyhedron` shapes from a neper-generated .tess file."""
        polyhedra: list[Polyhedron] = []
        tess = Neper.parse_tess(filename)
        for cell_index in range(tess["cells"]["number_of_cells"]):
            global_face_indices = tess["polyhedra"]["faces"][cell_index]
            global_vertex_indices: list[int] = []
            for face_ind in global_face_indices:
                global_vertex_indices += tess["faces"]["vertices"][face_ind - 1]
            global_vertex_indices = sorted(dict.fromkeys(global_vertex_indices))

            vertices: list[tuple[float, float, float]] = [
                (
                    tess["vertices"]["ver_x"][ind - 1],
                    tess["vertices"]["ver_y"][ind - 1],
                    tess["vertices"]["ver_z"][ind - 1],
                )
                for ind in global_vertex_indices
            ]

            faces: list[dict[str, list[int]]] = []
            for face_ind in global_face_indices:
                face_vertices = tess["faces"]["vertices"][face_ind - 1]
                faces.append(
                    {
                        "vertices": [
                            global_vertex_indices.index(v) for v in face_vertices
                        ],
                    },
                )

            polyhedra.append(Polyhedron(dic={"vertices": vertices, "faces": faces}))
        return polyhedra

    @staticmethod
    def parse_tess(filename: str) -> dict[str, dict]:
        """Parse a tessellation (.tess) file generated by neper.

        Returns a dictionary with keys ``cells``, ``vertices``, ``edges``,
        ``faces``, ``polyhedra``. Follows the .tess structure from
        `neper's documentation`_.

        .. _neper's documentation: https://neper.info/doc/fileformat.html#tessellation-file-tess
        """
        path = Path(filename)
        if path.suffix == "":
            path = path.with_suffix(".tess")
        with path.open() as f:
            for _ in range(6):
                f.readline()
            cells = Neper._read_cells(f)
            vertices = Neper._read_vertices(f)
            edges = Neper._read_edges(f)
            faces = Neper._read_faces(f)
            polyhedra = Neper._read_polyhedra(f)
        return {
            "cells": cells,
            "vertices": vertices,
            "edges": edges,
            "faces": faces,
            "polyhedra": polyhedra,
        }

    @staticmethod
    def _read_cells(f: TextIO) -> dict:
        cells: dict = {"number_of_cells": int(f.readline())}
        n = cells["number_of_cells"]
        while True:
            tag = f.readline().rstrip()
            if tag == "  *id":
                cells["id"] = Neper._read_int_block(f, n)
            elif tag in {"  *mode", "  *modeid"}:
                cells["mode"] = Neper._read_int_block(f, n)
            elif tag == "  *seed":
                cells["seed"] = [Neper._parse_seed_row(f.readline()) for _ in range(n)]
            elif tag == "  *ori":
                cells["ori"] = {"descriptor": f.readline()}
                for _ in range(n):
                    data = f.readline().split()
                    cells["ori"]["cellid_param"] = [float(x) for x in data[:3]]
            elif tag in {"  *orispread", "  *lam"}:
                pass
            elif tag == "  *crysym":
                cells["crysym"] = f.readline()
            elif tag == " **vertex":
                return cells
            else:
                err_msg = f"tag {tag} not known"
                raise ValueError(err_msg)

    @staticmethod
    def _read_int_block(f: TextIO, count: int) -> list[int]:
        values: list[int] = []
        while len(values) < count:
            values.extend(int(x) for x in f.readline().split())
        return values

    @staticmethod
    def _parse_seed_row(line: str) -> dict:
        data = line.split()
        return {
            "seed_id": int(data[0]),
            "seed_x": float(data[1]),
            "seed_y": float(data[2]),
            "seed_z": float(data[3]),
            "seed_weight": float(data[_TESS_SEED_WEIGHT_INDEX]),
        }

    @staticmethod
    def _read_vertices(f: TextIO) -> dict:
        n = int(f.readline())
        vertices: dict = {
            "total_number_of_vertices": n,
            "ver_id": [],
            "ver_x": [],
            "ver_y": [],
            "ver_z": [],
            "ver_state": [],
        }
        for _ in range(n):
            data = f.readline().split()
            vertices["ver_id"].append(int(data[0]))
            vertices["ver_x"].append(float(data[_TESS_VERTEX_X_INDEX]))
            vertices["ver_y"].append(float(data[_TESS_VERTEX_Y_INDEX]))
            vertices["ver_z"].append(float(data[_TESS_VERTEX_Z_INDEX]))
            vertices["ver_state"].append(int(data[_TESS_VERTEX_STATE_INDEX]))
        return vertices

    @staticmethod
    def _read_edges(f: TextIO) -> dict:
        f.readline()  # **edge
        n = int(f.readline().rstrip())
        edges: dict = {
            "total_number_of_edges": n,
            "edge_id": [],
            "ver_1": [],
            "ver_2": [],
            "edge_state": [],
        }
        for _ in range(n):
            data = f.readline().split()
            edges["edge_id"].append(int(data[0]))
            edges["ver_1"].append(int(data[1]))
            edges["ver_2"].append(int(data[2]))
            edges["edge_state"].append(int(data[3]))
        return edges

    @staticmethod
    def _read_faces(f: TextIO) -> dict:
        f.readline()  # **face
        n = int(f.readline().rstrip())
        faces: dict = {
            "total_number_of_faces": n,
            "face_id": [],
            "vertices": [],
            "edges": [],
        }
        for _ in range(n):
            data = f.readline().split()
            faces["face_id"].append(int(data[0]))
            n_ver = int(data[1])
            faces["vertices"].append([int(data[j + 2]) for j in range(n_ver)])
            data = f.readline().split()
            n_edg = int(data[0])
            faces["edges"].append(
                [int(np.abs(int(data[j + 1]))) for j in range(n_edg)],
            )
            f.readline()  # not reading this line
            f.readline()  # not reading this line
        return faces

    @staticmethod
    def _read_polyhedra(f: TextIO) -> dict:
        f.readline()  # **polyhedron
        n = int(f.readline().rstrip())
        polyhedra: dict = {
            "total_number_of_polyhedra": n,
            "poly_id": [],
            "faces": [],
        }
        for _ in range(n):
            data = f.readline().split()
            polyhedra["poly_id"].append(int(data[0]))
            n_fac = int(data[1])
            polyhedra["faces"].append(
                [int(np.abs(int(data[j + 2]))) for j in range(n_fac)],
            )
        return polyhedra


# ---------------------------------------------------------------------------
# Mmg
# ---------------------------------------------------------------------------


class MmgError(Exception):
    """Raised when an mmg command fails."""


class Mmg:
    """Wrapper around the ``mmg2d_O3`` / ``mmgs_O3`` / ``mmg3d_O3`` binaries.

    Each method exposes the underlying mmg CLI flags as keyword arguments
    using the same short names as the binaries themselves (``input``,
    ``output``, ``ls``, ``nr``, ``A``, ``ar``, ...). See the
    `mmg documentation <https://www.mmgtools.org/mmg-remesher-try-mmg/mmg-remesher-options>`_
    for the full reference.

    A larger redesign of this interface is planned; for now it intentionally
    mirrors the original flat-kwarg shape.
    """

    @staticmethod
    def _run_mmg_command(cmd: list[str]) -> None:
        try:
            subprocess.check_output(cmd, stderr=subprocess.STDOUT)
        except (subprocess.CalledProcessError, FileNotFoundError) as error:
            mmg_failed_command = " ".join(cmd)
            raise MmgError(
                f"mmg command '{mmg_failed_command}' failed",
            ) from error

    @staticmethod
    def mmg2d(
        d=None,
        h=None,
        m=None,
        v=None,
        val=None,
        default=None,
        input=None,
        output=None,
        solution=None,
        metric=None,
        A=None,
        ar=None,
        hausd=None,
        hgrad=None,
        hmax=None,
        hmin=None,
        hsiz=None,
        lag=None,
        ls=None,
        _3dMedit=None,
        noinsert=None,
        nomove=None,
        nosurf=None,
        noswap=None,
        nr=None,
        nreg=None,
        nsd=None,
        optim=None,
        opnbdy=None,
        rmc=None,
    ):
        """Run mmg2d_O3 from the command line with given arguments."""
        cmd = ["mmg2d_O3"]
        if d:
            cmd.append("-d")
        if h:
            cmd.append("-h")
        if m:
            if isinstance(m, bool):
                m = ""
            cmd.extend(["-m", str(m)])
        if v:
            if isinstance(v, bool):
                v = 1
            cmd.extend(["-v", str(v)])
        if val:
            cmd.append("-val")
        if default:
            cmd.append("-default")
        if input:
            cmd.extend(["-in", input])
        if output:
            cmd.extend(["-out", output])
        if solution:
            cmd.extend(["-sol", solution])
        if metric:
            cmd.extend(["-met", metric])
        if A:
            cmd.append("-A")
        if ar:
            cmd.extend(["-ar", str(ar)])
        if hausd:
            cmd.extend(["-hausd", str(hausd)])
        if hgrad:
            cmd.extend(["-hgrad", str(hgrad)])
        if hmax:
            cmd.extend(["-hmax", str(hmax)])
        if hmin:
            cmd.extend(["-hmin", str(hmin)])
        if hsiz:
            cmd.extend(["-hsiz", str(hsiz)])
        if lag or lag == 0:
            if isinstance(lag, bool):
                lag = 0
            cmd.extend(["-lag", str(lag)])
        if ls or ls == 0:
            ls_value = ls
            if isinstance(ls_value, bool):
                ls_value = 0
            cmd.extend(["-ls", str(ls_value)])
        if _3dMedit:
            cmd.extend(["-3dMedit", str(_3dMedit)])
        if noinsert:
            cmd.append("-noinsert")
        if nomove:
            cmd.append("-nomove")
        if nosurf:
            cmd.append("-nosurf")
        if noswap:
            cmd.append("-noswap")
        if nr:
            cmd.append("-nr")
        if nreg:
            cmd.extend(["-nreg", str(nreg)])
        if nsd:
            cmd.extend(["-nsd", str(nsd)])
        if optim:
            cmd.append("-optim")
        if opnbdy:
            cmd.append("-opnbdy")
        if rmc:
            cmd.extend(["-rmc", str(rmc)])

        Mmg._run_mmg_command(cmd)

    @staticmethod
    def mmgs(
        d=None,
        h=None,
        m=None,
        v=None,
        val=None,
        default=None,
        input=None,
        output=None,
        solution=None,
        metric=None,
        A=None,
        ar=None,
        hausd=None,
        hgrad=None,
        hmax=None,
        hmin=None,
        hsiz=None,
        ls=None,
        noinsert=None,
        nomove=None,
        nosurf=None,
        noswap=None,
        nr=None,
        nreg=None,
        nsd=None,
        optim=None,
        rn=None,
    ):
        """Run mmgs_O3 from the command line with given arguments."""
        cmd = ["mmgs_O3"]
        if d:
            cmd.append("-d")
        if h:
            cmd.append("-h")
        if m:
            if isinstance(m, bool):
                m = ""
            cmd.extend(["-m", str(m)])
        if v:
            if isinstance(v, bool):
                v = 1
            cmd.extend(["-v", str(v)])
        if val:
            cmd.append("-val")
        if default:
            cmd.append("-default")
        if input:
            cmd.extend(["-in", input])
        if output:
            cmd.extend(["-out", output])
        if solution:
            cmd.extend(["-sol", solution])
        if metric:
            cmd.extend(["-met", metric])
        if A:
            cmd.append("-A")
        if ar:
            cmd.extend(["-ar", str(ar)])
        if hausd:
            cmd.extend(["-hausd", str(hausd)])
        if hgrad:
            cmd.extend(["-hgrad", str(hgrad)])
        if hmax:
            cmd.extend(["-hmax", str(hmax)])
        if hmin:
            cmd.extend(["-hmin", str(hmin)])
        if hsiz:
            cmd.extend(["-hsiz", str(hsiz)])
        if ls or ls == 0:
            ls_value = ls
            if isinstance(ls_value, bool):
                ls_value = 0
            cmd.extend(["-ls", str(ls_value)])
        if noinsert:
            cmd.append("-noinsert")
        if nomove:
            cmd.append("-nomove")
        if nosurf:
            cmd.append("-nosurf")
        if noswap:
            cmd.append("-noswap")
        if nr:
            cmd.append("-nr")
        if nreg:
            cmd.extend(["-nreg", str(nreg)])
        if nsd:
            cmd.extend(["-nsd", str(nsd)])
        if optim:
            cmd.append("-optim")
        if rn:
            cmd.append("-rn")
        Mmg._run_mmg_command(cmd)

    @staticmethod
    def mmg3d(
        d=None,
        h=None,
        m=None,
        v=None,
        val=None,
        default=None,
        input=None,
        output=None,
        solution=None,
        metric=None,
        A=None,
        ar=None,
        octree=None,
        hausd=None,
        hgrad=None,
        hmax=None,
        hmin=None,
        hsiz=None,
        lag=None,
        ls=None,
        nofem=None,
        noinsert=None,
        nomove=None,
        nosurf=None,
        noswap=None,
        nr=None,
        nreg=None,
        nsd=None,
        optim=None,
        optimLES=None,
        opnbdy=None,
        rmc=None,
        rn=None,
    ):
        """Run mmg3d_O3 from the command line with given arguments."""
        cmd = ["mmg3d_O3"]
        if d:
            cmd.append("-d")
        if h:
            cmd.append("-h")
        if m:
            if isinstance(m, bool):
                m = ""
            cmd.extend(["-m", str(m)])
        if v:
            if isinstance(v, bool):
                v = 1
            cmd.extend(["-v", str(v)])
        if val:
            cmd.append("-val")
        if default:
            cmd.append("-default")
        if input:
            cmd.extend(["-in", input])
        if output:
            cmd.extend(["-out", output])
        if solution:
            cmd.extend(["-sol", solution])
        if metric:
            cmd.extend(["-met", metric])
        if A:
            cmd.append("-A")
        if ar:
            cmd.extend(["-ar", str(ar)])
        if octree:
            cmd.extend(["-octree", str(octree)])
        if hausd:
            cmd.extend(["-hausd", str(hausd)])
        if hgrad:
            cmd.extend(["-hgrad", str(hgrad)])
        if hmax:
            cmd.extend(["-hmax", str(hmax)])
        if hmin:
            cmd.extend(["-hmin", str(hmin)])
        if hsiz:
            cmd.extend(["-hsiz", str(hsiz)])
        if lag or lag == 0:
            if isinstance(lag, bool):
                lag = 0
            cmd.extend(["-lag", str(lag)])
        if ls or ls == 0:
            ls_value = ls
            if isinstance(ls_value, bool):
                ls_value = 0
            cmd.extend(["-ls", str(ls_value)])
        if nofem:
            cmd.append("-nofem")
        if noinsert:
            cmd.append("-noinsert")
        if nomove:
            cmd.append("-nomove")
        if nosurf:
            cmd.append("-nosurf")
        if noswap:
            cmd.append("-noswap")
        if nr:
            cmd.append("-nr")
        if nreg:
            cmd.extend(["-nreg", str(nreg)])
        if nsd:
            cmd.extend(["-nsd", str(nsd)])
        if optim:
            cmd.append("-optim")
        if optimLES:
            cmd.append("-optimLES")
        if opnbdy:
            cmd.append("-opnbdy")
        if rmc:
            cmd.extend(["-rmc", str(rmc)])
        if rn:
            cmd.append("-rn")

        Mmg._run_mmg_command(cmd)
