"""Wrappers around external command-line tools.

- `Neper - Polycrystal Generation and Meshing`_
- `mmg - Robust, Open-source & Multidisciplinary Software for Remeshing`_
  (via the ``mmgpy`` Python bindings — install with
  ``pip install mmgpy`` or ``conda install -c conda-forge mmgpy``)

.. _Neper - Polycrystal Generation and Meshing: https://neper.info/
.. _mmg - Robust, Open-source & Multidisciplinary Software for Remeshing: https://www.mmgtools.org/
"""

from __future__ import annotations

import shutil
import subprocess
import warnings
from pathlib import Path
from typing import TYPE_CHECKING, Any

import numpy as np

from microgen.shape import Polyhedron

if TYPE_CHECKING:
    from typing import TextIO

# Vertex-data row indices in the polyhedron-faces section of a .tess file.
_TESS_VERTEX_X_INDEX = 1
_TESS_VERTEX_Y_INDEX = 2
_TESS_VERTEX_Z_INDEX = 3
_TESS_VERTEX_STATE_INDEX = 4

# Seed-row index in the *cell seed* section.
_TESS_SEED_WEIGHT_INDEX = 4

_MMGPY_INSTALL_HINT = (
    "microgen's MMG remeshing path requires mmgpy. "
    "Install it with:  pip install mmgpy  "
    "or:  conda install -c conda-forge mmgpy"
)


def _require_mmgpy() -> Any:
    """Import :mod:`mmgpy` lazily and surface a helpful error otherwise."""
    try:
        import mmgpy  # noqa: PLC0415
    except ImportError as err:
        raise ImportError(_MMGPY_INSTALL_HINT) from err
    return mmgpy


# ---------------------------------------------------------------------------
# Neper
# ---------------------------------------------------------------------------


class Neper:
    """Wrapper around the ``neper`` command-line tool."""

    @staticmethod
    def run(
        filename: str,
        n_cells: int,
        cube_dim: tuple[float, float, float],
    ) -> None:
        r"""Run a neper tessellation from the command line.

        Equivalent to::

            neper -T -n n_cells -id 1 -dim 3 \
                  -domain 'cube(cube_dim[0], cube_dim[1], cube_dim[2])' \
                  -morpho gg -o filename

        :param filename: output file
        :param n_cells: number of cells of the tessellation
        :param cube_dim: see `neper's documentation`_

        .. _neper's documentation: https://neper.info/doc/neper_t.html#cmdoption-domain
        """
        neper = shutil.which("neper")
        if neper is None:
            warnings.warn(
                "Neper is not installed. "
                "Please install Neper before running this command.",
                stacklevel=2,
            )
            return

        try:
            subprocess.run([neper, "--version"], check=True)  # noqa: S603
        except subprocess.CalledProcessError:
            warnings.warn(
                "Neper is installed but '--version' failed.",
                stacklevel=2,
            )
            return

        cube = f"cube({cube_dim[0]},{cube_dim[1]},{cube_dim[2]})"
        command = [
            neper,
            "-T",
            "-n",
            str(n_cells),
            "-id",
            "1",
            "-dim",
            "3",
            "-domain",
            cube,
            "-morpho",
            "gg",
            "-o",
            filename,
        ]
        subprocess.run(command, check=True)  # noqa: S603

    @staticmethod
    def voronoi_from_tess_file(filename: str) -> list[Polyhedron]:
        """Build :class:`Polyhedron` shapes from a neper-generated .tess file."""
        polyhedra: list[Polyhedron] = []
        tess = Neper.parse_tess(filename)
        for cell_index in range(tess["cells"]["number_of_cells"]):
            global_face_indices = tess["polyhedra"]["faces"][cell_index]
            global_vertex_indices: list[int] = []
            for face_ind in global_face_indices:
                global_vertex_indices += tess["faces"]["vertices"][face_ind - 1]
            global_vertex_indices = sorted(dict.fromkeys(global_vertex_indices))

            vertices: list[tuple[float, float, float]] = [
                (
                    tess["vertices"]["ver_x"][ind - 1],
                    tess["vertices"]["ver_y"][ind - 1],
                    tess["vertices"]["ver_z"][ind - 1],
                )
                for ind in global_vertex_indices
            ]

            faces: list[dict[str, list[int]]] = []
            for face_ind in global_face_indices:
                face_vertices = tess["faces"]["vertices"][face_ind - 1]
                faces.append(
                    {
                        "vertices": [
                            global_vertex_indices.index(v) for v in face_vertices
                        ],
                    },
                )

            polyhedra.append(Polyhedron(dic={"vertices": vertices, "faces": faces}))
        return polyhedra

    @staticmethod
    def parse_tess(filename: str) -> dict[str, dict]:
        """Parse a tessellation (.tess) file generated by neper.

        Returns a dictionary with keys ``cells``, ``vertices``, ``edges``,
        ``faces``, ``polyhedra``. Follows the .tess structure from
        `neper's documentation`_.

        .. _neper's documentation: https://neper.info/doc/fileformat.html#tessellation-file-tess
        """
        path = Path(filename)
        if path.suffix == "":
            path = path.with_suffix(".tess")
        with path.open() as f:
            for _ in range(6):
                f.readline()
            cells = Neper._read_cells(f)
            vertices = Neper._read_vertices(f)
            edges = Neper._read_edges(f)
            faces = Neper._read_faces(f)
            polyhedra = Neper._read_polyhedra(f)
        return {
            "cells": cells,
            "vertices": vertices,
            "edges": edges,
            "faces": faces,
            "polyhedra": polyhedra,
        }

    @staticmethod
    def _read_cells(f: TextIO) -> dict:
        cells: dict = {"number_of_cells": int(f.readline())}
        n = cells["number_of_cells"]
        while True:
            tag = f.readline().rstrip()
            if tag == "  *id":
                cells["id"] = Neper._read_int_block(f, n)
            elif tag in {"  *mode", "  *modeid"}:
                cells["mode"] = Neper._read_int_block(f, n)
            elif tag == "  *seed":
                cells["seed"] = [Neper._parse_seed_row(f.readline()) for _ in range(n)]
            elif tag == "  *ori":
                cells["ori"] = {"descriptor": f.readline()}
                for _ in range(n):
                    data = f.readline().split()
                    cells["ori"]["cellid_param"] = [float(x) for x in data[:3]]
            elif tag in {"  *orispread", "  *lam"}:
                pass
            elif tag == "  *crysym":
                cells["crysym"] = f.readline()
            elif tag == " **vertex":
                return cells
            else:
                err_msg = f"tag {tag} not known"
                raise ValueError(err_msg)

    @staticmethod
    def _read_int_block(f: TextIO, count: int) -> list[int]:
        values: list[int] = []
        while len(values) < count:
            values.extend(int(x) for x in f.readline().split())
        return values

    @staticmethod
    def _parse_seed_row(line: str) -> dict:
        data = line.split()
        return {
            "seed_id": int(data[0]),
            "seed_x": float(data[1]),
            "seed_y": float(data[2]),
            "seed_z": float(data[3]),
            "seed_weight": float(data[_TESS_SEED_WEIGHT_INDEX]),
        }

    @staticmethod
    def _read_vertices(f: TextIO) -> dict:
        n = int(f.readline())
        vertices: dict = {
            "total_number_of_vertices": n,
            "ver_id": [],
            "ver_x": [],
            "ver_y": [],
            "ver_z": [],
            "ver_state": [],
        }
        for _ in range(n):
            data = f.readline().split()
            vertices["ver_id"].append(int(data[0]))
            vertices["ver_x"].append(float(data[_TESS_VERTEX_X_INDEX]))
            vertices["ver_y"].append(float(data[_TESS_VERTEX_Y_INDEX]))
            vertices["ver_z"].append(float(data[_TESS_VERTEX_Z_INDEX]))
            vertices["ver_state"].append(int(data[_TESS_VERTEX_STATE_INDEX]))
        return vertices

    @staticmethod
    def _read_edges(f: TextIO) -> dict:
        f.readline()  # **edge
        n = int(f.readline().rstrip())
        edges: dict = {
            "total_number_of_edges": n,
            "edge_id": [],
            "ver_1": [],
            "ver_2": [],
            "edge_state": [],
        }
        for _ in range(n):
            data = f.readline().split()
            edges["edge_id"].append(int(data[0]))
            edges["ver_1"].append(int(data[1]))
            edges["ver_2"].append(int(data[2]))
            edges["edge_state"].append(int(data[3]))
        return edges

    @staticmethod
    def _read_faces(f: TextIO) -> dict:
        f.readline()  # **face
        n = int(f.readline().rstrip())
        faces: dict = {
            "total_number_of_faces": n,
            "face_id": [],
            "vertices": [],
            "edges": [],
        }
        for _ in range(n):
            data = f.readline().split()
            faces["face_id"].append(int(data[0]))
            n_ver = int(data[1])
            faces["vertices"].append([int(data[j + 2]) for j in range(n_ver)])
            data = f.readline().split()
            n_edg = int(data[0])
            faces["edges"].append(
                [int(np.abs(int(data[j + 1]))) for j in range(n_edg)],
            )
            f.readline()  # not reading this line
            f.readline()  # not reading this line
        return faces

    @staticmethod
    def _read_polyhedra(f: TextIO) -> dict:
        f.readline()  # **polyhedron
        n = int(f.readline().rstrip())
        polyhedra: dict = {
            "total_number_of_polyhedra": n,
            "poly_id": [],
            "faces": [],
        }
        for _ in range(n):
            data = f.readline().split()
            polyhedra["poly_id"].append(int(data[0]))
            n_fac = int(data[1])
            polyhedra["faces"].append(
                [int(np.abs(int(data[j + 2]))) for j in range(n_fac)],
            )
        return polyhedra


# ---------------------------------------------------------------------------
# Mmg
# ---------------------------------------------------------------------------


class MmgError(Exception):
    """Raised when an Mmg invocation fails."""


# CLI flag → mmgpy option-key translation.  Most flags map 1:1 to mmgpy's
# options dict; two flags use renamed keys (``-nr`` → ``angle=0`` disables
# ridge detection; ``-A`` → ``anisosize=1`` requests anisotropic adaptation).
_SKIP = object()


def _as_float(v: Any) -> Any:
    return _SKIP if v is None or v is False else float(v)


def _as_int_or_one(v: Any) -> Any:
    return _SKIP if v is None or v is False else (1 if v is True else int(v))


def _as_int_or_zero(v: Any) -> Any:
    return _SKIP if v is None or v is False else (0 if v is True else int(v))


def _as_float_or_zero(v: Any) -> Any:
    return _SKIP if v is None or v is False else (0.0 if v is True else float(v))


def _as_presence(v: Any) -> Any:
    return 1 if v else _SKIP


def _as_angle_zero(v: Any) -> Any:
    return 0 if v else _SKIP


_FLAG_SPEC: dict[str, tuple[str, Any]] = {
    # Numeric / value-carrying.
    "hausd": ("hausd", _as_float),
    "hgrad": ("hgrad", _as_float),
    "hmax": ("hmax", _as_float),
    "hmin": ("hmin", _as_float),
    "hsiz": ("hsiz", _as_float),
    "rmc": ("rmc", _as_float),
    "ar": ("ar", _as_float),
    # Bool-true → 1, otherwise int cast; some keys are renamed.
    "v": ("verbose", _as_int_or_one),
    "m": ("mem", _as_int_or_one),
    "nreg": ("nreg", _as_int_or_one),
    "nsd": ("nsd", _as_int_or_one),
    "octree": ("octree", _as_int_or_one),
    # 0 is meaningful (bool-true defaults to 0).
    "lag": ("lag", _as_int_or_zero),
    "ls": ("ls", _as_float_or_zero),
    # Boolean / presence-only.
    "noinsert": ("noinsert", _as_presence),
    "nomove": ("nomove", _as_presence),
    "nosurf": ("nosurf", _as_presence),
    "noswap": ("noswap", _as_presence),
    "optim": ("optim", _as_presence),
    "optimLES": ("optimLES", _as_presence),
    "opnbdy": ("opnbdy", _as_presence),
    "nofem": ("nofem", _as_presence),
    # CLI synonyms with renamed option keys.
    "A": ("anisosize", _as_presence),
    "rn": ("renum", _as_presence),
    "nr": ("angle", _as_angle_zero),
}


def _build_mmg_options(flag_kwargs: dict[str, Any]) -> dict[str, Any]:
    """Translate Mmg CLI-style kwargs into an ``mmgpy`` options dict."""
    opts: dict[str, Any] = {}
    for raw_key, raw_val in flag_kwargs.items():
        spec = _FLAG_SPEC.get(raw_key)
        if spec is None:
            continue
        out_key, mapper = spec
        result = mapper(raw_val)
        if result is not _SKIP:
            opts[out_key] = result
    return opts


def _run_mmg(
    binding_name: str,
    *,
    input_mesh: str | None,
    output_mesh: str | None,
    solution: str | None,
    metric: str | None,
    options: dict[str, Any],
) -> None:
    """Invoke ``mmgpy.{mmg2d,mmgs,mmg3d}.remesh`` and re-raise as MmgError.

    The ``input_mesh is None`` guard runs *before* :func:`_require_mmgpy` so
    the historical "no-args raises MmgError" contract is preserved even on
    machines without mmgpy installed.
    """
    if input_mesh is None:
        err_msg = f"Mmg.{binding_name} requires an input mesh path (input=...)"
        raise MmgError(err_msg)

    mmgpy = _require_mmgpy()
    binding = getattr(mmgpy, binding_name)
    try:
        binding.remesh(
            input_mesh=input_mesh,
            input_sol=solution,
            input_met=metric,
            output_mesh=output_mesh,
            options=options,
        )
    except Exception as err:  # noqa: BLE001
        raise MmgError(f"mmg invocation failed: {err}") from err


class Mmg:
    """Thin wrapper around :mod:`mmgpy` with a CLI-style keyword interface.

    Each static method accepts CLI-named keyword arguments (``input``,
    ``output``, ``hausd``, ``hgrad``, …), translates them to an ``mmgpy``
    options dict, and forwards to :func:`mmgpy.mmg{2d,s,3d}.remesh`.
    """

    @staticmethod
    def mmg2d(
        m=None,
        v=None,
        input=None,
        output=None,
        solution=None,
        metric=None,
        A=None,
        ar=None,
        hausd=None,
        hgrad=None,
        hmax=None,
        hmin=None,
        hsiz=None,
        lag=None,
        ls=None,
        noinsert=None,
        nomove=None,
        nosurf=None,
        noswap=None,
        nr=None,
        nreg=None,
        nsd=None,
        optim=None,
        opnbdy=None,
        rmc=None,
    ):
        """Run mmg2d on ``input`` writing to ``output``.

        Forwards to :func:`mmgpy.mmg2d.remesh`.
        """
        opts = _build_mmg_options(
            {
                "m": m,
                "v": v,
                "A": A,
                "ar": ar,
                "hausd": hausd,
                "hgrad": hgrad,
                "hmax": hmax,
                "hmin": hmin,
                "hsiz": hsiz,
                "lag": lag,
                "ls": ls,
                "noinsert": noinsert,
                "nomove": nomove,
                "nosurf": nosurf,
                "noswap": noswap,
                "nr": nr,
                "nreg": nreg,
                "nsd": nsd,
                "optim": optim,
                "opnbdy": opnbdy,
                "rmc": rmc,
            },
        )
        _run_mmg(
            "mmg2d",
            input_mesh=input,
            output_mesh=output,
            solution=solution,
            metric=metric,
            options=opts,
        )

    @staticmethod
    def mmgs(
        m=None,
        v=None,
        input=None,
        output=None,
        solution=None,
        metric=None,
        A=None,
        ar=None,
        hausd=None,
        hgrad=None,
        hmax=None,
        hmin=None,
        hsiz=None,
        ls=None,
        noinsert=None,
        nomove=None,
        nosurf=None,
        noswap=None,
        nr=None,
        nreg=None,
        nsd=None,
        optim=None,
        rn=None,
    ):
        """Run mmgs (surface remesher) on ``input`` writing to ``output``.

        Forwards to :func:`mmgpy.mmgs.remesh`.
        """
        opts = _build_mmg_options(
            {
                "m": m,
                "v": v,
                "A": A,
                "ar": ar,
                "hausd": hausd,
                "hgrad": hgrad,
                "hmax": hmax,
                "hmin": hmin,
                "hsiz": hsiz,
                "ls": ls,
                "noinsert": noinsert,
                "nomove": nomove,
                "nosurf": nosurf,
                "noswap": noswap,
                "nr": nr,
                "nreg": nreg,
                "nsd": nsd,
                "optim": optim,
                "rn": rn,
            },
        )
        _run_mmg(
            "mmgs",
            input_mesh=input,
            output_mesh=output,
            solution=solution,
            metric=metric,
            options=opts,
        )

    @staticmethod
    def mmg3d(
        m=None,
        v=None,
        input=None,
        output=None,
        solution=None,
        metric=None,
        A=None,
        ar=None,
        octree=None,
        hausd=None,
        hgrad=None,
        hmax=None,
        hmin=None,
        hsiz=None,
        lag=None,
        ls=None,
        nofem=None,
        noinsert=None,
        nomove=None,
        nosurf=None,
        noswap=None,
        nr=None,
        nreg=None,
        nsd=None,
        optim=None,
        optimLES=None,
        opnbdy=None,
        rmc=None,
        rn=None,
    ):
        """Run mmg3d (volume remesher) on ``input`` writing to ``output``.

        Forwards to :func:`mmgpy.mmg3d.remesh`.
        """
        opts = _build_mmg_options(
            {
                "m": m,
                "v": v,
                "A": A,
                "ar": ar,
                "octree": octree,
                "hausd": hausd,
                "hgrad": hgrad,
                "hmax": hmax,
                "hmin": hmin,
                "hsiz": hsiz,
                "lag": lag,
                "ls": ls,
                "nofem": nofem,
                "noinsert": noinsert,
                "nomove": nomove,
                "nosurf": nosurf,
                "noswap": noswap,
                "nr": nr,
                "nreg": nreg,
                "nsd": nsd,
                "optim": optim,
                "optimLES": optimLES,
                "opnbdy": opnbdy,
                "rmc": rmc,
                "rn": rn,
            },
        )
        _run_mmg(
            "mmg3d",
            input_mesh=input,
            output_mesh=output,
            solution=solution,
            metric=metric,
            options=opts,
        )
